import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { ChevronRight, Info } from "lucide-react";

type MethodologyDetailsProps = {
  methodology: string;
};

const MethodologyDetails: React.FC<MethodologyDetailsProps> = ({ methodology }) => {
  if (methodology === "mmm") {
    return <MarketingMixModelingDetails />;
  } else if (methodology === "incrementality") {
    return <IncrementalityTestingDetails />;
  } else if (methodology === "mta") {
    return <MultiTouchAttributionDetails />;
  }
  
  return null;
};

const FormulaBlock = ({ formula, description }: { formula: string, description?: React.ReactNode }) => {
  return (
    <div className="my-4">
      <div className="p-5 bg-gradient-to-r from-indigo-50 to-blue-50 rounded-md font-mono text-center border border-indigo-100 shadow-sm">
        <div className="text-lg text-indigo-900 font-semibold">{formula}</div>
      </div>
      {description && (
        <div className="mt-3 text-muted-foreground text-sm">
          {description}
        </div>
      )}
    </div>
  );
};

const DefinitionList = ({ items }: { items: { term: string; definition: string }[] }) => {
  return (
    <div className="space-y-3 my-4">
      {items.map((item, index) => (
        <div key={index} className="flex gap-3 items-start border-b border-dashed border-indigo-100 pb-2">
          <div className="font-medium text-indigo-800 w-24 flex-shrink-0">{item.term}:</div>
          <div className="text-muted-foreground">{item.definition}</div>
        </div>
      ))}
    </div>
  );
};

const InfoBox = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="bg-blue-50 border-l-4 border-blue-500 p-4 rounded-md my-4 flex gap-3">
      <Info className="w-5 h-5 text-blue-500 flex-shrink-0 mt-0.5" />
      <div className="text-blue-900 text-sm">{children}</div>
    </div>
  );
};

const MarketingMixModelingDetails = () => {
  return (
    <Card className="mb-6 border-t-4 border-t-blue-500">
      <CardHeader className="bg-gradient-to-r from-blue-50/50 to-indigo-50/50">
        <CardTitle className="text-2xl">Marketing Mix Modeling (MMM) - Technical Deep Dive</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6 pt-6">
        <Tabs defaultValue="overview">
          <TabsList className="bg-slate-100 p-1 rounded-lg mb-2 w-full grid grid-cols-4">
            <TabsTrigger value="overview" className="rounded-md">Overview</TabsTrigger>
            <TabsTrigger value="mathematics" className="rounded-md">Mathematical Foundation</TabsTrigger>
            <TabsTrigger value="implementation" className="rounded-md">Implementation</TabsTrigger>
            <TabsTrigger value="advanced" className="rounded-md">Advanced Techniques</TabsTrigger>
          </TabsList>
          
          <TabsContent value="overview" className="space-y-6 mt-6 animate-fade-in">
            <div>
              <h3 className="text-lg font-semibold mb-2 text-blue-700 flex items-center gap-2">
                <span className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center text-blue-700">1</span>
                Technical Definition
              </h3>
              <p className="leading-relaxed">Marketing Mix Modeling (MMM) is a statistical analysis technique used to quantify the impact of various marketing tactics on sales or other KPIs. It uses time-series regression analysis to establish a relationship between marketing activities and business outcomes, accounting for external factors.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-3 text-blue-700 flex items-center gap-2">
                <span className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center text-blue-700">2</span>
                Core Components
              </h3>
              <div className="grid md:grid-cols-2 gap-4">
                <ul className="list-none space-y-2">
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center shrink-0 font-medium">•</div>
                    <div>
                      <span className="font-medium text-blue-800">Base Sales:</span>
                      <p className="text-muted-foreground text-sm">Predicted sales without any marketing spend</p>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center shrink-0 font-medium">•</div>
                    <div>
                      <span className="font-medium text-blue-800">Incremental Sales:</span>
                      <p className="text-muted-foreground text-sm">Additional sales generated by marketing activities</p>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center shrink-0 font-medium">•</div>
                    <div>
                      <span className="font-medium text-blue-800">Decay Factors:</span>
                      <p className="text-muted-foreground text-sm">How long the effect of marketing lasts</p>
                    </div>
                  </li>
                </ul>
                <ul className="list-none space-y-2">
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center shrink-0 font-medium">•</div>
                    <div>
                      <span className="font-medium text-blue-800">Adstock Effects:</span>
                      <p className="text-muted-foreground text-sm">Carryover effects from previous marketing periods</p>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center shrink-0 font-medium">•</div>
                    <div>
                      <span className="font-medium text-blue-800">Synergy Effects:</span>
                      <p className="text-muted-foreground text-sm">Interaction between different marketing channels</p>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center shrink-0 font-medium">•</div>
                    <div>
                      <span className="font-medium text-blue-800">Control Variables:</span>
                      <p className="text-muted-foreground text-sm">External factors like seasonality, competitors, pricing</p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-3 text-blue-700 flex items-center gap-2">
                <span className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center text-blue-700">3</span>
                Data Requirements
              </h3>
              <div className="bg-slate-50 rounded-xl p-5 border border-slate-200">
                <ul className="list-none grid md:grid-cols-2 gap-4">
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center shrink-0 font-medium">1</div>
                    <div>
                      <span className="font-medium">Time-series data</span>
                      <p className="text-sm text-muted-foreground">(typically 2-3 years of weekly or monthly data)</p>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center shrink-0 font-medium">2</div>
                    <div>
                      <span className="font-medium">Marketing spend by channel</span>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center shrink-0 font-medium">3</div>
                    <div>
                      <span className="font-medium">Sales or other KPI data</span>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center shrink-0 font-medium">4</div>
                    <div>
                      <span className="font-medium">External factors</span>
                      <p className="text-sm text-muted-foreground">(seasons, holidays, promotions, competitor activities)</p>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center shrink-0 font-medium">5</div>
                    <div>
                      <span className="font-medium">Pricing information</span>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center shrink-0 font-medium">6</div>
                    <div>
                      <span className="font-medium">Macroeconomic indicators</span>
                      <p className="text-sm text-muted-foreground">(if relevant)</p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </TabsContent>
          
          <TabsContent value="mathematics" className="space-y-6 mt-6 animate-fade-in">
            <div>
              <h3 className="text-xl font-semibold mb-4 text-blue-700 border-b pb-2 border-blue-100">Mathematical Foundation of MMM</h3>
              
              <div className="bg-white rounded-xl shadow-sm border p-6 space-y-6">
                <div>
                  <h4 className="text-lg font-semibold mb-3 text-blue-800">Basic Regression Model</h4>
                  <p className="mb-3">At its core, MMM uses a multiple regression model of the form:</p>
                  
                  <FormulaBlock 
                    formula="Y = β₀ + β₁X₁ + β₂X₂ + ... + βₙXₙ + ε" 
                    description={
                      <DefinitionList items={[
                        { term: "Y", definition: "Target variable (sales, conversions, etc.)" },
                        { term: "β₀", definition: "Baseline (sales without marketing)" },
                        { term: "β₁...βₙ", definition: "Coefficients representing effectiveness of each channel" },
                        { term: "X₁...Xₙ", definition: "Marketing spending or activity in each channel" },
                        { term: "ε", definition: "Error term" }
                      ]} />
                    }
                  />
                </div>
                
                <div>
                  <h4 className="text-lg font-semibold mb-3 text-blue-800">Adstock Transformation</h4>
                  <p className="mb-3">Adstock accounts for lagged and diminishing effects of advertising over time:</p>
                  
                  <FormulaBlock 
                    formula="A_t = X_t + λ·A_{t-1}" 
                    description={
                      <DefinitionList items={[
                        { term: "A_t", definition: "Adstock at time t" },
                        { term: "X_t", definition: "Marketing spend at time t" },
                        { term: "λ", definition: "Decay rate (0 to 1)" },
                        { term: "A_{t-1}", definition: "Previous period's adstock" }
                      ]} />
                    }
                  />
                  
                  <InfoBox>
                    The adstock transformation captures how advertising continues to have an effect after the initial exposure, 
                    gradually diminishing over time. Higher λ values mean longer-lasting effects.
                  </InfoBox>
                </div>
                
                <div>
                  <h4 className="text-lg font-semibold mb-3 text-blue-800">Saturation Effects (Diminishing Returns)</h4>
                  <p className="mb-3">Often modeled using a Hill function or similar S-curve:</p>
                  
                  <FormulaBlock 
                    formula="S(A_t) = A_t^α / (K^α + A_t^α)" 
                    description={
                      <DefinitionList items={[
                        { term: "S(A_t)", definition: "Saturated response" },
                        { term: "A_t", definition: "Adstock value" },
                        { term: "α", definition: "Shape parameter" },
                        { term: "K", definition: "Half-saturation constant" }
                      ]} />
                    }
                  />
                  
                  <div className="mt-4 flex gap-4 p-4 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg">
                    <div className="w-32 h-32 bg-white rounded-md border border-blue-200 flex items-center justify-center p-2">
                      <svg viewBox="0 0 100 100" className="w-full h-full">
                        <path d="M10,90 C10,90 10,50 10,50 C10,20 30,10 50,10 C70,10 90,20 90,50 C90,50 90,90 90,90" fill="none" stroke="#4F46E5" strokeWidth="2" />
                        <line x1="10" y1="90" x2="90" y2="90" stroke="#6B7280" strokeWidth="1" />
                        <line x1="10" y1="10" x2="10" y2="90" stroke="#6B7280" strokeWidth="1" />
                        <text x="95" y="90" fontSize="8" fill="#6B7280">Investment</text>
                        <text x="5" y="5" fontSize="8" fill="#6B7280">Return</text>
                      </svg>
                    </div>
                    <div className="flex-1">
                      <h5 className="font-medium text-blue-800 mb-1">Diminishing Returns Curve</h5>
                      <p className="text-sm text-muted-foreground">
                        This S-curve shows how marketing effectiveness diminishes as spend increases. 
                        Initially, more spend yields proportionally large returns, but eventually 
                        additional spending produces smaller and smaller incremental effects as the market saturates.
                      </p>
                    </div>
                  </div>
                </div>
                
                <div>
                  <h4 className="text-lg font-semibold mb-3 text-blue-800">Complete Multiplicative Model</h4>
                  <p className="mb-3">A full MMM might look like:</p>
                  
                  <FormulaBlock 
                    formula="Y_t = β₀·∏(1 + S_i(A_{i,t}))·∏(1 + Control_j) + ε_t" 
                    description={
                      <p>This multiplicative form captures interactions between variables better than additive models,
                      allowing for synergistic effects between channels and controlling factors.</p>
                    }
                  />
                </div>
              </div>
            </div>
          </TabsContent>
          
          <TabsContent value="implementation" className="space-y-4 mt-6 animate-fade-in">
            <div>
              <h3 className="text-lg font-semibold mb-4 text-blue-700 border-b pb-2 border-blue-100">Implementation Process</h3>
              
              <div className="bg-white p-6 rounded-xl shadow-sm border">
                <ol className="list-none space-y-4">
                  {[
                    { title: "Data collection and cleaning", desc: "Gather all relevant data sources and prepare them for analysis" },
                    { title: "Feature engineering", desc: "Create adstock transformations, seasonality components, and other derived variables" },
                    { title: "Model selection", desc: "Choose between linear, multiplicative, or hierarchical model structures" },
                    { title: "Parameter estimation", desc: "Use OLS, MLE, or Bayesian methods to fit model parameters" },
                    { title: "Validation", desc: "Test model accuracy using cross-validation and hold-out testing" },
                    { title: "Interpretation", desc: "Decompose effects to understand channel contributions" },
                    { title: "Optimization", desc: "Use model outputs to recommend optimal budget allocations" }
                  ].map((step, index) => (
                    <li key={index} className="flex gap-4">
                      <div className="w-12 h-12 rounded-full bg-blue-100 text-blue-800 flex items-center justify-center font-semibold shrink-0">
                        {index + 1}
                      </div>
                      <div>
                        <h4 className="font-medium text-blue-900">{step.title}</h4>
                        <p className="text-muted-foreground">{step.desc}</p>
                      </div>
                    </li>
                  ))}
                </ol>
              </div>
            </div>
            
            <div className="grid md:grid-cols-2 gap-6 mt-6">
              <div>
                <h3 className="text-lg font-semibold mb-3 text-blue-700">Common Statistical Packages</h3>
                <div className="bg-slate-50 rounded-lg p-4 border border-slate-200 h-full">
                  <ul className="list-none space-y-3">
                    <li className="flex gap-3 items-center">
                      <div className="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center shrink-0 font-medium">R</div>
                      <div>
                        <span className="font-medium">R packages</span>
                        <p className="text-sm text-muted-foreground">Robyn (Facebook's MMM package)</p>
                      </div>
                    </li>
                    <li className="flex gap-3 items-center">
                      <div className="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center shrink-0 font-medium">Py</div>
                      <div>
                        <span className="font-medium">Python</span>
                        <p className="text-sm text-muted-foreground">LightweightMMM, PyMC3 for Bayesian models</p>
                      </div>
                    </li>
                    <li className="flex gap-3 items-center">
                      <div className="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center shrink-0 font-medium">C</div>
                      <div>
                        <span className="font-medium">Commercial tools</span>
                        <p className="text-sm text-muted-foreground">Nielsen, IRI, Google 360</p>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
              
              <div>
                <h3 className="text-lg font-semibold mb-3 text-blue-700">Validation Techniques</h3>
                <div className="bg-slate-50 rounded-lg p-4 border border-slate-200 h-full">
                  <ul className="grid grid-cols-2 gap-3">
                    <li className="flex gap-2 items-center">
                      <div className="w-2 h-2 rounded-full bg-blue-500 shrink-0"></div>
                      <div className="text-sm">Adjusted R-squared</div>
                    </li>
                    <li className="flex gap-2 items-center">
                      <div className="w-2 h-2 rounded-full bg-blue-500 shrink-0"></div>
                      <div className="text-sm">Root Mean Square Error (RMSE)</div>
                    </li>
                    <li className="flex gap-2 items-center">
                      <div className="w-2 h-2 rounded-full bg-blue-500 shrink-0"></div>
                      <div className="text-sm">Mean Absolute Percentage Error</div>
                    </li>
                    <li className="flex gap-2 items-center">
                      <div className="w-2 h-2 rounded-full bg-blue-500 shrink-0"></div>
                      <div className="text-sm">Holdout sample testing</div>
                    </li>
                    <li className="flex gap-2 items-center">
                      <div className="w-2 h-2 rounded-full bg-blue-500 shrink-0"></div>
                      <div className="text-sm">Backtesting on historical data</div>
                    </li>
                    <li className="flex gap-2 items-center">
                      <div className="w-2 h-2 rounded-full bg-blue-500 shrink-0"></div>
                      <div className="text-sm">Comparison with experiments</div>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </TabsContent>
          
          <TabsContent value="advanced" className="space-y-6 mt-6 animate-fade-in">
            <div className="grid md:grid-cols-2 gap-6">
              {[
                {
                  title: "Bayesian MMM",
                  desc: "Bayesian approaches use prior distributions for model parameters and produce posterior distributions rather than point estimates. They better handle uncertainty and can incorporate business knowledge as priors."
                },
                {
                  title: "Hierarchical Models",
                  desc: "Allow modeling at multiple levels (e.g., national and regional) simultaneously, sharing information between levels while allowing for local differences."
                },
                {
                  title: "Automated MMM",
                  desc: "Recent approaches use neural networks and automated machine learning to estimate marketing effects, often incorporating raw data like creatives, keywords, etc."
                },
                {
                  title: "Geo-based MMM",
                  desc: "Uses variations in marketing activity across geographic regions to identify causal effects, similar to a quasi-experimental design."
                }
              ].map((technique, index) => (
                <div key={index} className="bg-gradient-to-br from-white to-blue-50 rounded-xl p-6 border border-blue-100 shadow-sm">
                  <h3 className="text-lg font-semibold mb-3 text-blue-700">{technique.title}</h3>
                  <p className="text-muted-foreground">{technique.desc}</p>
                </div>
              ))}
            </div>
            
            <div className="bg-gradient-to-br from-indigo-50 to-blue-50 rounded-xl p-6 border border-indigo-100 mt-6">
              <h3 className="text-lg font-semibold mb-4 text-indigo-800">Integration with Other Methods</h3>
              <p className="mb-4">Modern approaches integrate MMM with other measurement techniques to create unified frameworks:</p>
              
              <div className="grid grid-cols-3 gap-4">
                <div className="bg-white rounded-lg p-4 shadow-sm">
                  <div className="text-center mb-3">
                    <div className="w-12 h-12 rounded-full bg-blue-100 flex items-center justify-center mx-auto">
                      <span className="font-bold text-blue-700">MMM</span>
                    </div>
                  </div>
                  <p className="text-sm text-center">Strategic channel planning</p>
                </div>
                
                <div className="bg-white rounded-lg p-4 shadow-sm">
                  <div className="text-center mb-3">
                    <div className="w-12 h-12 rounded-full bg-purple-100 flex items-center justify-center mx-auto">
                      <span className="font-bold text-purple-700">MTA</span>
                    </div>
                  </div>
                  <p className="text-sm text-center">Customer journey insights</p>
                </div>
                
                <div className="bg-white rounded-lg p-4 shadow-sm">
                  <div className="text-center mb-3">
                    <div className="w-12 h-12 rounded-full bg-green-100 flex items-center justify-center mx-auto">
                      <span className="font-bold text-green-700">Inc</span>
                    </div>
                  </div>
                  <p className="text-sm text-center">Causal validation</p>
                </div>
              </div>
              
              <div className="mt-4 text-sm text-indigo-800 text-center font-medium">
                Unified measurement frameworks leverage the strengths of each method to provide a complete view of marketing performance
              </div>
            </div>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
};

// Expanded Incrementality Testing details
const IncrementalityTestingDetails = () => {
  return (
    <Card className="mb-6 border-t-4 border-t-purple-500">
      <CardHeader className="bg-gradient-to-r from-purple-50/50 to-indigo-50/50">
        <CardTitle className="text-2xl">Incrementality Testing - Technical Deep Dive</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6 pt-6">
        <Tabs defaultValue="overview">
          <TabsList className="bg-slate-100 p-1 rounded-lg mb-2 w-full grid grid-cols-4">
            <TabsTrigger value="overview" className="rounded-md">Overview</TabsTrigger>
            <TabsTrigger value="mathematics" className="rounded-md">Mathematical Foundation</TabsTrigger>
            <TabsTrigger value="implementation" className="rounded-md">Implementation</TabsTrigger>
            <TabsTrigger value="advanced" className="rounded-md">Advanced Techniques</TabsTrigger>
          </TabsList>
          
          <TabsContent value="overview" className="space-y-6 mt-6 animate-fade-in">
            <div>
              <h3 className="text-lg font-semibold mb-2 text-purple-700 flex items-center gap-2">
                <span className="w-8 h-8 rounded-full bg-purple-100 flex items-center justify-center text-purple-700">1</span>
                Technical Definition
              </h3>
              <p className="leading-relaxed">Incrementality testing is an experimental approach to measure the causal impact of marketing interventions by comparing outcomes between treatment and control groups. It aims to isolate the true lift attributable to a specific marketing activity.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-3 text-purple-700 flex items-center gap-2">
                <span className="w-8 h-8 rounded-full bg-purple-100 flex items-center justify-center text-purple-700">2</span>
                Core Components
              </h3>
              <div className="grid md:grid-cols-2 gap-4">
                <ul className="list-none space-y-2">
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center shrink-0 font-medium">•</div>
                    <div>
                      <span className="font-medium text-purple-800">Treatment Group:</span>
                      <p className="text-muted-foreground text-sm">Users exposed to the marketing activity</p>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center shrink-0 font-medium">•</div>
                    <div>
                      <span className="font-medium text-purple-800">Control Group:</span>
                      <p className="text-muted-foreground text-sm">Similar users not exposed to the activity</p>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center shrink-0 font-medium">•</div>
                    <div>
                      <span className="font-medium text-purple-800">Randomization:</span>
                      <p className="text-muted-foreground text-sm">Process of assigning users to groups</p>
                    </div>
                  </li>
                </ul>
                <ul className="list-none space-y-2">
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center shrink-0 font-medium">•</div>
                    <div>
                      <span className="font-medium text-purple-800">Lift Measurement:</span>
                      <p className="text-muted-foreground text-sm">Calculation of the difference in outcomes</p>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center shrink-0 font-medium">•</div>
                    <div>
                      <span className="font-medium text-purple-800">Statistical Significance:</span>
                      <p className="text-muted-foreground text-sm">Confidence that results are not due to chance</p>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center shrink-0 font-medium">•</div>
                    <div>
                      <span className="font-medium text-purple-800">Sample Size:</span>
                      <p className="text-muted-foreground text-sm">Number of users needed for reliable results</p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-3 text-purple-700 flex items-center gap-2">
                <span className="w-8 h-8 rounded-full bg-purple-100 flex items-center justify-center text-purple-700">3</span>
                Experimental Designs
              </h3>
              <div className="bg-slate-50 rounded-xl p-5 border border-slate-200">
                <ul className="list-none grid md:grid-cols-2 gap-4">
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center shrink-0 font-medium">1</div>
                    <div>
                      <span className="font-medium">PSA Tests</span>
                      <p className="text-sm text-muted-foreground">Compare real ads to public service announcements</p>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center shrink-0 font-medium">2</div>
                    <div>
                      <span className="font-medium">Ghost Ads</span>
                      <p className="text-sm text-muted-foreground">Tag potential impressions without showing ads</p>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center shrink-0 font-medium">3</div>
                    <div>
                      <span className="font-medium">Intent-to-Treat</span>
                      <p className="text-sm text-muted-foreground">Analyze by assignment, not actual exposure</p>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center shrink-0 font-medium">4</div>
                    <div>
                      <span className="font-medium">Geo-based Experiments</span>
                      <p className="text-sm text-muted-foreground">Vary exposure by geographic region</p>
                    </div>
                  </li>
                  <li className="flex gap-3 items-start">
                    <div className="w-6 h-6 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center shrink-0 font-medium">5</div>
                    <div>
                      <span className="font-medium">Holdout Tests</span>
                      <p className="text-sm text-muted-foreground">Exclude a portion of audience from campaigns</p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </TabsContent>
          
          <TabsContent value="mathematics" className="space-y-6 mt-6 animate-fade-in">
            <div>
              <h3 className="text-xl font-semibold mb-4 text-purple-700 border-b pb-2 border-purple-100">Mathematical Foundation of Incrementality Testing</h3>
              
              <div className="bg-white rounded-xl shadow-sm border p-6 space-y-6">
                <div>
                  <h4 className="text-
