
import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { ChevronRight } from "lucide-react";

type MethodologyDetailsProps = {
  methodology: string;
};

const MethodologyDetails: React.FC<MethodologyDetailsProps> = ({ methodology }) => {
  if (methodology === "mmm") {
    return <MarketingMixModelingDetails />;
  } else if (methodology === "incrementality") {
    return <IncrementalityTestingDetails />;
  } else if (methodology === "mta") {
    return <MultiTouchAttributionDetails />;
  }
  
  return null;
};

const MarketingMixModelingDetails = () => {
  return (
    <Card className="mb-6">
      <CardHeader>
        <CardTitle className="text-2xl">Marketing Mix Modeling (MMM) - Technical Deep Dive</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        <Tabs defaultValue="overview">
          <TabsList>
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="mathematics">Mathematical Foundation</TabsTrigger>
            <TabsTrigger value="implementation">Implementation</TabsTrigger>
            <TabsTrigger value="advanced">Advanced Techniques</TabsTrigger>
          </TabsList>
          
          <TabsContent value="overview" className="space-y-4 mt-4">
            <div>
              <h3 className="text-lg font-semibold mb-2">Technical Definition</h3>
              <p>Marketing Mix Modeling (MMM) is a statistical analysis technique used to quantify the impact of various marketing tactics on sales or other KPIs. It uses time-series regression analysis to establish a relationship between marketing activities and business outcomes, accounting for external factors.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Core Components</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>Base Sales: Predicted sales without any marketing spend</li>
                <li>Incremental Sales: Additional sales generated by marketing activities</li>
                <li>Decay Factors: How long the effect of marketing lasts</li>
                <li>Adstock Effects: Carryover effects from previous marketing periods</li>
                <li>Synergy Effects: Interaction between different marketing channels</li>
                <li>Control Variables: External factors like seasonality, competitors, pricing</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Data Requirements</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>Time-series data (typically 2-3 years of weekly or monthly data)</li>
                <li>Marketing spend by channel</li>
                <li>Sales or other KPI data</li>
                <li>External factors (seasons, holidays, promotions, competitor activities)</li>
                <li>Pricing information</li>
                <li>Macroeconomic indicators if relevant</li>
              </ul>
            </div>
          </TabsContent>
          
          <TabsContent value="mathematics" className="space-y-4 mt-4">
            <div>
              <h3 className="text-lg font-semibold mb-2">Basic Regression Model</h3>
              <p className="mb-2">At its core, MMM uses a multiple regression model of the form:</p>
              <div className="p-4 bg-muted rounded-md font-mono">
                Y = β₀ + β₁X₁ + β₂X₂ + ... + βₙXₙ + ε
              </div>
              <ul className="list-disc pl-6 mt-4 space-y-2">
                <li>Y: Target variable (sales, conversions, etc.)</li>
                <li>β₀: Baseline (sales without marketing)</li>
                <li>β₁...βₙ: Coefficients representing effectiveness of each channel</li>
                <li>X₁...Xₙ: Marketing spending or activity in each channel</li>
                <li>ε: Error term</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Adstock Transformation</h3>
              <p className="mb-2">Adstock accounts for lagged and diminishing effects of advertising over time:</p>
              <div className="p-4 bg-muted rounded-md font-mono">
                A_t = X_t + λ·A_{'{'}t-1{'}'}
              </div>
              <p className="mt-2">Where:</p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>A_t: Adstock at time t</li>
                <li>X_t: Marketing spend at time t</li>
                <li>λ: Decay rate (0 to 1)</li>
                <li>A_{'{'}t-1{'}'}: Previous period's adstock</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Saturation Effects (Diminishing Returns)</h3>
              <p className="mb-2">Often modeled using a Hill function or similar S-curve:</p>
              <div className="p-4 bg-muted rounded-md font-mono">
                S(A_t) = A_t^α / (K^α + A_t^α)
              </div>
              <p className="mt-2">Where:</p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>S(A_t): Saturated response</li>
                <li>A_t: Adstock value</li>
                <li>α: Shape parameter</li>
                <li>K: Half-saturation constant</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Complete Multiplicative Model</h3>
              <p className="mb-2">A full MMM might look like:</p>
              <div className="p-4 bg-muted rounded-md font-mono">
                Y_t = β₀·∏(1 + S_i(A_{'{'}i,t{'}'}))·∏(1 + Control_j) + ε_t
              </div>
              <p className="mt-2">This multiplicative form captures interactions between variables better than additive models.</p>
            </div>
          </TabsContent>
          
          <TabsContent value="implementation" className="space-y-4 mt-4">
            <div>
              <h3 className="text-lg font-semibold mb-2">Modeling Process</h3>
              <ol className="list-decimal pl-6 space-y-2">
                <li>Data collection and cleaning</li>
                <li>Feature engineering (adstock transformations, seasonality components)</li>
                <li>Model selection (linear, multiplicative, hierarchical)</li>
                <li>Parameter estimation (typically using OLS, MLE, or Bayesian methods)</li>
                <li>Validation (cross-validation, hold-out testing)</li>
                <li>Interpretation and decomposition of effects</li>
                <li>Optimization and simulation</li>
              </ol>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Common Statistical Packages</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>R: Specialized packages like 'Robyn' (Facebook's MMM package)</li>
                <li>Python: 'LightweightMMM', 'PyMC3' for Bayesian models</li>
                <li>Commercial tools: Nielsen, IRI, Google 360</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Validation Techniques</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>Adjusted R-squared</li>
                <li>Root Mean Square Error (RMSE)</li>
                <li>Mean Absolute Percentage Error (MAPE)</li>
                <li>Holdout sample testing</li>
                <li>Backtesting on historical data</li>
                <li>Comparison with experimental results</li>
              </ul>
            </div>
          </TabsContent>
          
          <TabsContent value="advanced" className="space-y-4 mt-4">
            <div>
              <h3 className="text-lg font-semibold mb-2">Bayesian MMM</h3>
              <p>Bayesian approaches use prior distributions for model parameters and produce posterior distributions rather than point estimates. They better handle uncertainty and can incorporate business knowledge as priors.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Hierarchical Models</h3>
              <p>Allow modeling at multiple levels (e.g., national and regional) simultaneously, sharing information between levels while allowing for local differences.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Automated MMM</h3>
              <p>Recent approaches use neural networks and automated machine learning to estimate marketing effects, often incorporating raw data like creatives, keywords, etc.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Geo-based MMM</h3>
              <p>Uses variations in marketing activity across geographic regions to identify causal effects, similar to a quasi-experimental design.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Integration with Other Methods</h3>
              <p>Modern approaches integrate MMM with MTA and incrementality testing to create unified measurement frameworks that leverage strengths of each method.</p>
            </div>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
};

const IncrementalityTestingDetails = () => {
  return (
    <Card className="mb-6">
      <CardHeader>
        <CardTitle className="text-2xl">Incrementality Testing - Technical Deep Dive</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        <Tabs defaultValue="overview">
          <TabsList>
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="mathematics">Mathematical Foundation</TabsTrigger>
            <TabsTrigger value="implementation">Implementation</TabsTrigger>
            <TabsTrigger value="advanced">Advanced Techniques</TabsTrigger>
          </TabsList>
          
          <TabsContent value="overview" className="space-y-4 mt-4">
            <div>
              <h3 className="text-lg font-semibold mb-2">Technical Definition</h3>
              <p>Incrementality testing is an experimental approach to measure the causal impact of marketing interventions by comparing outcomes between treatment and control groups. It aims to isolate the true lift attributable to a specific marketing activity.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Core Components</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>Treatment Group: Users exposed to the marketing activity</li>
                <li>Control Group: Similar users not exposed to the activity</li>
                <li>Randomization: Process of assigning users to groups</li>
                <li>Lift Measurement: Calculation of the difference in outcomes</li>
                <li>Statistical Significance: Confidence that results are not due to chance</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Experimental Designs</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>PSA Tests: Compare real ads to public service announcements</li>
                <li>Ghost Ads: Tag potential impressions without showing ads</li>
                <li>Intent-to-Treat: Analyze by assignment, not actual exposure</li>
                <li>Geo-based Experiments: Vary exposure by geographic region</li>
                <li>Holdout Tests: Exclude a portion of audience from campaigns</li>
              </ul>
            </div>
          </TabsContent>
          
          <TabsContent value="mathematics" className="space-y-4 mt-4">
            <div>
              <h3 className="text-lg font-semibold mb-2">Causal Inference Framework</h3>
              <p className="mb-2">The fundamental concept in incrementality testing comes from the Rubin Causal Model:</p>
              <div className="p-4 bg-muted rounded-md font-mono">
                Causal Effect = E[Y(1)] - E[Y(0)]
              </div>
              <p className="mt-2">Where:</p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>Y(1): Potential outcome if treated</li>
                <li>Y(0): Potential outcome if not treated</li>
                <li>E[]: Expected value</li>
              </ul>
              <p className="mt-2">Since we can't observe both Y(1) and Y(0) for the same unit (the fundamental problem of causal inference), we use randomization to create statistically equivalent groups.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Average Treatment Effect (ATE)</h3>
              <div className="p-4 bg-muted rounded-md font-mono">
                ATE = E[Y | T=1] - E[Y | T=0]
              </div>
              <p className="mt-2">Where:</p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>E[Y | T=1]: Expected outcome for treatment group</li>
                <li>E[Y | T=0]: Expected outcome for control group</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Relative Lift Calculation</h3>
              <div className="p-4 bg-muted rounded-md font-mono">
                Relative Lift = (Y₁ - Y₀) / Y₀ = (ATE / E[Y | T=0])
              </div>
              <p className="mt-2">Where:</p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>Y₁: Conversion rate in treatment group</li>
                <li>Y₀: Conversion rate in control group</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Statistical Significance</h3>
              <p className="mb-2">To determine if the observed lift is statistically significant:</p>
              <div className="p-4 bg-muted rounded-md font-mono">
                z = (p₁ - p₀) / sqrt(p(1-p)(1/n₁ + 1/n₀))
              </div>
              <p className="mt-2">Where:</p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>p₁: Conversion rate in treatment group</li>
                <li>p₀: Conversion rate in control group</li>
                <li>p: Pooled proportion (combined conversion rate)</li>
                <li>n₁: Sample size of treatment group</li>
                <li>n₀: Sample size of control group</li>
              </ul>
              <p className="mt-2">We typically reject the null hypothesis (no effect) if |z| {'>'} 1.96 (for 95% confidence).</p>
            </div>
          </TabsContent>
          
          <TabsContent value="implementation" className="space-y-4 mt-4">
            <div>
              <h3 className="text-lg font-semibold mb-2">Experimental Design Process</h3>
              <ol className="list-decimal pl-6 space-y-2">
                <li>Define clear hypotheses and metrics</li>
                <li>Determine required sample size via power analysis</li>
                <li>Design randomization procedure</li>
                <li>Set experiment duration</li>
                <li>Implement technical infrastructure for group assignment</li>
                <li>Execute the experiment</li>
                <li>Collect and analyze data</li>
                <li>Interpret results and make decisions</li>
              </ol>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Sample Size Determination</h3>
              <p className="mb-2">For a two-sample test of proportions:</p>
              <div className="p-4 bg-muted rounded-md font-mono">
                n = (Z_α/2 + Z_β)² × [p₁(1-p₁) + p₀(1-p₀)] / (p₁-p₀)²
              </div>
              <p className="mt-2">Where:</p>
              <ul className="list-disc pl-6 mt-2 space-y-2">
                <li>Z_α/2: Z-score for desired significance level</li>
                <li>Z_β: Z-score for desired power</li>
                <li>p₁: Expected conversion rate in treatment</li>
                <li>p₀: Expected conversion rate in control</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Technical Implementation Methods</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>Cookie-based assignment</li>
                <li>User ID hashing for consistent assignment</li>
                <li>Geo-based targeting</li>
                <li>Platform-specific tools (Facebook Test & Learn, Google Experiments)</li>
                <li>Server-side vs. client-side randomization</li>
              </ul>
            </div>
          </TabsContent>
          
          <TabsContent value="advanced" className="space-y-4 mt-4">
            <div>
              <h3 className="text-lg font-semibold mb-2">CUPED (Controlled-experiment Using Pre-Experiment Data)</h3>
              <p>A variance reduction technique that uses pre-experiment data as a covariate to increase test sensitivity, allowing for shorter experiment durations or smaller sample sizes.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Stratified Sampling</h3>
              <p>Divides the population into strata and samples from each stratum to ensure balance on important covariates, reducing variance and increasing precision.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Multi-Cell Testing</h3>
              <p>Tests multiple treatments simultaneously to efficiently explore the parameter space, often using factorial designs or multi-armed bandit approaches.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Switchback Testing</h3>
              <p>Alternates between treatment and control in the same market/audience over time, useful when user-level randomization is not possible or when strong network effects exist.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Synthetic Control Methods</h3>
              <p>Creates a synthetic control group by weighting untreated units to match the treated unit's pre-treatment characteristics, useful when randomization is not possible.</p>
            </div>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
};

const MultiTouchAttributionDetails = () => {
  return (
    <Card className="mb-6">
      <CardHeader>
        <CardTitle className="text-2xl">Multi-Touch Attribution (MTA) - Technical Deep Dive</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        <Tabs defaultValue="overview">
          <TabsList>
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="mathematics">Mathematical Foundation</TabsTrigger>
            <TabsTrigger value="implementation">Implementation</TabsTrigger>
            <TabsTrigger value="advanced">Advanced Techniques</TabsTrigger>
          </TabsList>
          
          <TabsContent value="overview" className="space-y-4 mt-4">
            <div>
              <h3 className="text-lg font-semibold mb-2">Technical Definition</h3>
              <p>Multi-Touch Attribution (MTA) is a set of methods that assign credit to multiple marketing touchpoints along the customer journey that lead to a conversion. It uses user-level path data to determine the relative importance of each touchpoint.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Core Components</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>User Journey Tracking: Collection of sequential touchpoint data</li>
                <li>Attribution Models: Rules or algorithms for credit assignment</li>
                <li>Channel Weights: Relative importance assigned to each touchpoint</li>
                <li>Conversion Paths: Sequences of interactions leading to conversions</li>
                <li>Lookback Windows: Time period considered for attribution</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Data Requirements</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>User-level interaction data (cookies, device IDs, user IDs)</li>
                <li>Timestamp for each interaction</li>
                <li>Channel/campaign/creative identifiers</li>
                <li>Conversion events with values</li>
                <li>Cost data for ROI calculation</li>
              </ul>
            </div>
          </TabsContent>
          
          <TabsContent value="mathematics" className="space-y-4 mt-4">
            <div>
              <h3 className="text-lg font-semibold mb-2">Heuristic Models</h3>
              <p className="mb-2">Rule-based attribution models assign credit based on predefined rules:</p>
              <ol className="list-decimal pl-6 space-y-2">
                <li>
                  <strong>Last-Touch:</strong>
                  <div className="p-4 bg-muted rounded-md font-mono">
                    Credit(i) = 1 if i = last touchpoint, 0 otherwise
                  </div>
                </li>
                <li>
                  <strong>First-Touch:</strong>
                  <div className="p-4 bg-muted rounded-md font-mono">
                    Credit(i) = 1 if i = first touchpoint, 0 otherwise
                  </div>
                </li>
                <li>
                  <strong>Linear:</strong>
                  <div className="p-4 bg-muted rounded-md font-mono">
                    Credit(i) = 1/n for all n touchpoints
                  </div>
                </li>
                <li>
                  <strong>Time-Decay:</strong>
                  <div className="p-4 bg-muted rounded-md font-mono">
                    Credit(i) = λ^(T-t_i) / Σ(λ^(T-t_j))
                  </div>
                  <p className="mt-2">Where λ is decay factor, T is conversion time, t_i is touchpoint time</p>
                </li>
                <li>
                  <strong>Position-Based:</strong>
                  <div className="p-4 bg-muted rounded-md font-mono">
                    Credit(i) = 0.4 if i = first or last, 0.2/(n-2) for others
                  </div>
                </li>
              </ol>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Algorithmic Models</h3>
              <p className="mb-2">Data-driven approaches to attribution:</p>
              <ol className="list-decimal pl-6 space-y-2">
                <li>
                  <strong>Markov Chains:</strong>
                  <p>Models the customer journey as a stochastic process with transition probabilities between states.</p>
                  <div className="p-4 bg-muted rounded-md font-mono">
                    Credit(i) = Σ(P(conversion|path with i) - P(conversion|path without i))
                  </div>
                </li>
                <li>
                  <strong>Shapley Value:</strong>
                  <p>Cooperative game theory approach that averages marginal contributions across all possible orderings.</p>
                  <div className="p-4 bg-muted rounded-md font-mono">
                    φ_i = Σ [|S|!(n-|S|-1)!/n!] × [v(S∪{'{'}i{'}'}) - v(S)]
                  </div>
                  <p className="mt-2">Where S is a subset of channels excluding i, v is the value function</p>
                </li>
                <li>
                  <strong>Logistic Regression:</strong>
                  <div className="p-4 bg-muted rounded-md font-mono">
                    log(p/(1-p)) = β₀ + β₁X₁ + β₂X₂ + ... + βₙXₙ
                  </div>
                  <p className="mt-2">Where X_i is an indicator of touchpoint i, β_i is its weight</p>
                </li>
              </ol>
            </div>
          </TabsContent>
          
          <TabsContent value="implementation" className="space-y-4 mt-4">
            <div>
              <h3 className="text-lg font-semibold mb-2">Implementation Process</h3>
              <ol className="list-decimal pl-6 space-y-2">
                <li>Data collection and integration from multiple sources</li>
                <li>User identity resolution across channels and devices</li>
                <li>Path analysis and pattern identification</li>
                <li>Model selection based on business objectives</li>
                <li>Model training and validation</li>
                <li>Credit assignment calculation</li>
                <li>Optimization and actionability</li>
              </ol>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Technical Challenges</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>Cookie deprecation and privacy regulations</li>
                <li>Cross-device tracking limitations</li>
                <li>Walled gardens and data silos</li>
                <li>Online-to-offline connection</li>
                <li>Data sparsity in individual paths</li>
                <li>Model validation without ground truth</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Implementation Tools</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>Google Analytics 360 (data-driven attribution)</li>
                <li>Adobe Analytics (algorithmic attribution)</li>
                <li>Custom implementations (R, Python)</li>
                <li>Specialized vendors (Neustar, Visual IQ, etc.)</li>
                <li>CDP platforms with attribution capabilities</li>
              </ul>
            </div>
          </TabsContent>
          
          <TabsContent value="advanced" className="space-y-4 mt-4">
            <div>
              <h3 className="text-lg font-semibold mb-2">Survival Analysis Models</h3>
              <p>Uses time-to-event modeling to understand how marketing touchpoints affect the probability and timing of conversion.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Deep Learning Approaches</h3>
              <p>Neural networks (especially RNNs, LSTMs) can model sequential touchpoint data and capture complex non-linear interactions between channels.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Counterfactual Methods</h3>
              <p>Use causal inference techniques to estimate what would have happened in the absence of specific touchpoints, similar to incrementality testing.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">Probabilistic Models with Bayesian Inference</h3>
              <p>Incorporate prior knowledge and produce distributions of attribution credits rather than point estimates, better handling uncertainty.</p>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-2">MTA-MMM Integration</h3>
              <p>Unified approaches that combine the granularity of MTA with the completeness of MMM, often using hierarchical models that share information between the two.</p>
            </div>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
};

export default MethodologyDetails;
